import type { Language } from '$lib/stores/docker';

// Settings view types
export type SettingsView = 'main' | 'profile' | 'security' | 'notifications' | 'appearance' | 'language' | 'data' | 'about' | 'users';

// Theme type
export type Theme = 'dark' | 'light' | 'system';

// Settings translations - Complete i18n
export const settingsText: Record<Language, Record<string, string>> = {
	es: {
		settings: 'Configuración',
		profile: 'Mi Perfil',
		profileDesc: 'Gestiona tu información personal',
		password: 'Cambiar Contraseña',
		passwordDesc: 'Actualiza tu contraseña de acceso',
		notifications: 'Notificaciones',
		notificationsDesc: 'Configura alertas y umbrales',
		appearance: 'Apariencia',
		appearanceDesc: 'Personaliza el tema visual',
		language: 'Idioma',
		languageDesc: 'Selecciona el idioma de la interfaz',
		data: 'Datos y Almacenamiento',
		dataDesc: 'Gestiona caché y datos locales',
		about: 'Acerca de',
		aboutDesc: 'Información de la aplicación',
		logout: 'Cerrar Sesión',
		back: 'Volver',
		save: 'Guardar',
		cancel: 'Cancelar',
		// Users
		users: 'Usuarios',
		usersDesc: 'Gestionar usuarios del sistema',
		addUser: '+ Agregar Usuario',
		loading: 'Cargando...',
		// Profile
		firstName: 'Nombre',
		lastName: 'Apellido',
		email: 'Correo electrónico',
		username: 'Nombre de usuario',
		changeAvatar: 'Cambiar avatar',
		// Password
		currentPassword: 'Contraseña actual',
		newPassword: 'Nueva contraseña',
		confirmPassword: 'Confirmar contraseña',
		passwordMismatch: 'Las contraseñas no coinciden',
		passwordChanged: 'Contraseña actualizada correctamente',
		passwordRequirements: 'Mínimo 8 caracteres, una mayúscula y un número',
		// Notifications
		alertThresholds: 'Umbrales de Alerta',
		cpuThreshold: 'Umbral de CPU',
		memoryThreshold: 'Umbral de Memoria',
		containerStopped: 'Contenedor detenido',
		containerStoppedDesc: 'Notificar cuando un contenedor se detenga',
		containerStarted: 'Contenedor iniciado',
		containerStartedDesc: 'Notificar cuando un contenedor se inicie',
		highCpu: 'CPU Alta',
		highCpuDesc: 'Alertar cuando CPU supere el umbral',
		highMemory: 'Memoria Alta',
		highMemoryDesc: 'Alertar cuando memoria supere el umbral',
		testNotification: 'Probar Notificación',
		sending: 'Enviando...',
		// Apprise / Notification Channels
		apprise: 'Apprise',
		appriseDesc: 'Servicios de notificación',
		appriseServer: 'Servidor Apprise',
		appriseUrl: 'URL de Apprise',
		appriseKey: 'Clave (para notificaciones con estado)',
		appriseHelp: 'Configura las URLs de notificación en tu servidor Apprise. Soporta Telegram, Email, Discord, Slack y más de 100 servicios.',
		sendTestNotification: 'Enviar Notificación de Prueba',
		notificationChannels: 'Canales de Notificación',
		emailNotifications: 'Notificaciones por Email',
		emailNotificationsDesc: 'Recibir alertas por correo electrónico',
		telegramNotifications: 'Notificaciones de Telegram',
		telegramNotificationsDesc: 'Recibir alertas por Telegram',
		telegramUrl: 'URL de Telegram (Apprise)',
		telegramUrlPlaceholder: 'tgram://token/chat_id',
		telegramUrlHelp: 'Formato: tgram://BOT_TOKEN/CHAT_ID',
		testChannelLabel: 'Canal de Prueba',
		testTelegram: 'Telegram',
		testEmail: 'Email',
		testBoth: 'Ambos',
		// Appearance
		dark: 'Oscuro',
		light: 'Claro',
		system: 'Sistema',
		themeSelect: 'Selecciona un tema',
		showStopped: 'Mostrar contenedores detenidos',
		showStoppedDesc: 'Incluir contenedores detenidos en el dashboard',
		highlightUpdates: 'Resaltar actualizaciones',
		highlightUpdatesDesc: 'Resaltar contenedores con actualizaciones disponibles',
		timeFormat: 'Formato de hora',
		dateFormat: 'Formato de fecha',
		lightTheme: 'Tema claro',
		darkTheme: 'Tema oscuro',
		font: 'Fuente',
		fontSize: 'Tamaño de fuente',
		gridFontSize: 'Tamaño fuente grid',
		terminalFont: 'Fuente terminal',
		small: 'Pequeño',
		normal: 'Normal',
		large: 'Grande',
		displaySettings: 'Configuración de Pantalla',
		themeSettings: 'Configuración de Tema',
		// Environments
		environments: 'Entornos',
		environmentsDesc: 'Gestionar conexiones Docker',
		addEnvironment: 'Agregar Entorno',
		testAll: 'Probar Todos',
		connectionType: 'Tipo de Conexión',
		unixSocket: 'Socket Unix',
		directTcp: 'TCP Directo',
		socketPath: 'Ruta del Socket',
		hostPort: 'Host:Puerto',
		general: 'General',
		updates: 'Actualizaciones',
		activity: 'Actividad',
		testConnection: 'Probar Conexión',
		editEnvironment: 'Editar Entorno',
		deleteEnvironment: 'Eliminar Entorno',
		autoUpdate: 'Actualización Automática',
		updateSchedule: 'Programación',
		imagePrune: 'Limpieza de Imágenes',
		eventTracking: 'Seguimiento de Eventos',
		vulnScanning: 'Escaneo de Vulnerabilidades',
		// Data
		clearCache: 'Limpiar caché',
		clearCacheDesc: 'Elimina datos temporales almacenados',
		exportData: 'Exportar datos',
		exportDataDesc: 'Descarga tu configuración',
		deleteAccount: 'Eliminar cuenta',
		deleteAccountDesc: 'Elimina permanentemente tu cuenta',
		cacheCleared: 'Caché eliminada correctamente',
		// About
		version: 'Versión',
		buildDate: 'Fecha de build',
		developer: 'Desarrollado por',
		license: 'Licencia',
		documentation: 'Documentación',
		reportBug: 'Reportar un problema',
		// Security / 2FA
		security: 'Seguridad',
		securityDesc: 'Contraseña y autenticación de dos factores',
		twoFactorAuth: 'Autenticación de Dos Factores (2FA)',
		twoFactorDesc: 'Añade una capa extra de seguridad a tu cuenta',
		twoFactorEnabled: '2FA Activado',
		twoFactorDisabled: '2FA Desactivado',
		enable2FA: 'Activar 2FA',
		disable2FA: 'Desactivar 2FA',
		setup2FA: 'Configurar 2FA',
		verify2FA: 'Verificar código',
		scanQRCode: 'Escanea el código QR con tu app de autenticación',
		manualEntry: 'O ingresa manualmente este código:',
		enterCode: 'Ingresa el código de 6 dígitos',
		recoveryCodes: 'Códigos de Recuperación',
		recoveryCodesDesc: 'Guarda estos códigos en un lugar seguro. Úsalos si pierdes acceso a tu app de autenticación.',
		regenerateCodes: 'Regenerar Códigos',
		codesRemaining: 'códigos restantes',
		invalidCode: 'Código inválido',
		confirmDisableTitle: 'Desactivar 2FA',
		confirmDisableDesc: '¿Estás seguro de que deseas desactivar la autenticación de dos factores?',
		enterPassword: 'Ingresa tu contraseña para confirmar',
		// Auto-logout
		autoLogout: 'Cierre de sesión automático',
		autoLogoutDesc: 'Cerrar sesión después de un período de inactividad',
		autoLogoutDisabled: 'Desactivado',
		autoLogoutMinutes: 'minutos',
		autoLogoutHour: 'hora',
		autoLogoutHours: 'horas',
	},
	en: {
		settings: 'Settings',
		profile: 'My Profile',
		profileDesc: 'Manage your personal information',
		password: 'Change Password',
		passwordDesc: 'Update your access password',
		notifications: 'Notifications',
		notificationsDesc: 'Configure alerts and thresholds',
		appearance: 'Appearance',
		appearanceDesc: 'Customize the visual theme',
		language: 'Language',
		languageDesc: 'Select the interface language',
		data: 'Data & Storage',
		dataDesc: 'Manage cache and local data',
		about: 'About',
		aboutDesc: 'Application information',
		logout: 'Sign Out',
		back: 'Back',
		save: 'Save',
		cancel: 'Cancel',
		// Users
		users: 'Users',
		usersDesc: 'Manage system users',
		addUser: '+ Add User',
		loading: 'Loading...',
		// Profile
		firstName: 'First Name',
		lastName: 'Last Name',
		email: 'Email',
		username: 'Username',
		changeAvatar: 'Change avatar',
		// Password
		currentPassword: 'Current password',
		newPassword: 'New password',
		confirmPassword: 'Confirm password',
		passwordMismatch: 'Passwords do not match',
		passwordChanged: 'Password updated successfully',
		passwordRequirements: 'Minimum 8 characters, one uppercase and one number',
		// Notifications
		alertThresholds: 'Alert Thresholds',
		cpuThreshold: 'CPU Threshold',
		memoryThreshold: 'Memory Threshold',
		containerStopped: 'Container stopped',
		containerStoppedDesc: 'Notify when a container stops',
		containerStarted: 'Container started',
		containerStartedDesc: 'Notify when a container starts',
		highCpu: 'High CPU',
		highCpuDesc: 'Alert when CPU exceeds threshold',
		highMemory: 'High Memory',
		highMemoryDesc: 'Alert when memory exceeds threshold',
		testNotification: 'Test Notification',
		sending: 'Sending...',
		// Apprise / Notification Channels
		apprise: 'Apprise',
		appriseDesc: 'Notification services',
		appriseServer: 'Apprise Server',
		appriseUrl: 'Apprise URL',
		appriseKey: 'Key (for stateful notifications)',
		appriseHelp: 'Configure notification URLs in your Apprise server. Supports Telegram, Email, Discord, Slack, and 100+ services.',
		sendTestNotification: 'Send Test Notification',
		notificationChannels: 'Notification Channels',
		emailNotifications: 'Email Notifications',
		emailNotificationsDesc: 'Receive alerts via email',
		telegramNotifications: 'Telegram Notifications',
		telegramNotificationsDesc: 'Receive alerts via Telegram',
		telegramUrl: 'Telegram URL (Apprise)',
		telegramUrlPlaceholder: 'tgram://token/chat_id',
		telegramUrlHelp: 'Format: tgram://BOT_TOKEN/CHAT_ID',
		testChannelLabel: 'Test Channel',
		testTelegram: 'Telegram',
		testEmail: 'Email',
		testBoth: 'Both',
		// Appearance
		dark: 'Dark',
		light: 'Light',
		system: 'System',
		themeSelect: 'Select a theme',
		showStopped: 'Show stopped containers',
		showStoppedDesc: 'Include stopped containers in the dashboard',
		highlightUpdates: 'Highlight available updates',
		highlightUpdatesDesc: 'Highlight containers with available updates',
		timeFormat: 'Time format',
		dateFormat: 'Date format',
		lightTheme: 'Light theme',
		darkTheme: 'Dark theme',
		font: 'Font',
		fontSize: 'Font size',
		gridFontSize: 'Grid font size',
		terminalFont: 'Terminal font',
		small: 'Small',
		normal: 'Normal',
		large: 'Large',
		displaySettings: 'Display Settings',
		themeSettings: 'Theme Settings',
		// Environments
		environments: 'Environments',
		environmentsDesc: 'Manage Docker connections',
		addEnvironment: 'Add Environment',
		testAll: 'Test All',
		connectionType: 'Connection Type',
		unixSocket: 'Unix Socket',
		directTcp: 'Direct TCP',
		socketPath: 'Socket Path',
		hostPort: 'Host:Port',
		general: 'General',
		updates: 'Updates',
		activity: 'Activity',
		testConnection: 'Test Connection',
		editEnvironment: 'Edit Environment',
		deleteEnvironment: 'Delete Environment',
		autoUpdate: 'Auto Update',
		updateSchedule: 'Schedule',
		imagePrune: 'Image Pruning',
		eventTracking: 'Event Tracking',
		vulnScanning: 'Vulnerability Scanning',
		// Data
		clearCache: 'Clear cache',
		clearCacheDesc: 'Delete stored temporary data',
		exportData: 'Export data',
		exportDataDesc: 'Download your configuration',
		deleteAccount: 'Delete account',
		deleteAccountDesc: 'Permanently delete your account',
		cacheCleared: 'Cache cleared successfully',
		// About
		version: 'Version',
		buildDate: 'Build date',
		developer: 'Developed by',
		license: 'License',
		documentation: 'Documentation',
		reportBug: 'Report a bug',
		// Security / 2FA
		security: 'Security',
		securityDesc: 'Password and two-factor authentication',
		twoFactorAuth: 'Two-Factor Authentication (2FA)',
		twoFactorDesc: 'Add an extra layer of security to your account',
		twoFactorEnabled: '2FA Enabled',
		twoFactorDisabled: '2FA Disabled',
		enable2FA: 'Enable 2FA',
		disable2FA: 'Disable 2FA',
		setup2FA: 'Setup 2FA',
		verify2FA: 'Verify code',
		scanQRCode: 'Scan the QR code with your authenticator app',
		manualEntry: 'Or manually enter this code:',
		enterCode: 'Enter the 6-digit code',
		recoveryCodes: 'Recovery Codes',
		recoveryCodesDesc: 'Save these codes in a safe place. Use them if you lose access to your authenticator app.',
		regenerateCodes: 'Regenerate Codes',
		codesRemaining: 'codes remaining',
		invalidCode: 'Invalid code',
		confirmDisableTitle: 'Disable 2FA',
		confirmDisableDesc: 'Are you sure you want to disable two-factor authentication?',
		enterPassword: 'Enter your password to confirm',
		// Auto-logout
		autoLogout: 'Auto Logout',
		autoLogoutDesc: 'Sign out after a period of inactivity',
		autoLogoutDisabled: 'Disabled',
		autoLogoutMinutes: 'minutes',
		autoLogoutHour: 'hour',
		autoLogoutHours: 'hours',
	}
};
